linters:
  enable:
  - gofumpt
  - goimports
  - misspell
  - revive

linters-settings:
  gofumpt:
    extra-rules: true
  gosimple:
    checks:
    - "all"
    # This check is poorly documented: https://staticcheck.io/docs/checks#S1034
    - "-S1034"

run:
  skip-dirs:
  - tint
