version: "3"

services:
  rhel8: &service
    image: dalibo/buildpack-pkg:rockylinux8
    volumes:
    - ../:/workspace
    working_dir: /workspace
    entrypoint: [/usr/local/sbin/tini]
    command: [/workspace/packaging/build_rpm.sh]

  rhel7:
    <<: *service
    image: dalibo/buildpack-pkg:centos7

  rhel6:
    <<: *service
    image: dalibo/buildpack-pkg:centos6
